<a href="https://colab.research.google.com/github/comandi1969/AIFFEL_Online_Quest/blob/main/ML_With_Python/%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EA%B8%B0%EC%B4%88_%EB%85%B8%EB%93%9C4_%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    '메뉴': ['[인기]아이펠치킨','닭강정','간장치킨','마늘치킨','파닭','승일양념치킨','양념반후라이드반','황금후라이드','[베스트]풀잎치킨'],
    '가격': [16000,15000,14000,14000,14000,13000,13000,12000,9900],
    '호수' : [11,12,9,9,11,10,10,10,10],
    '칼로리' : [1200.0,1500.0,1600.0,1800.0,1300.0,1400.0,1300.0,1000.0,1000.0],
    '할인율' : [0.5,0.2,0.2,0.2,0.2,0.2,0.2,0.2,np.nan],
    '할인가' : [8000.0,12000.0,11200.0,11200.0,11200.0,10400.0,10400.0,9600.0,np.nan],
    '원산지' : ['국내산','브라질','국내산','국내산','브라질','국내산','국내산','국내산','국내산'],
    '살찔까요' : ['no','yes','yes','yes','yes','yes','yes','no','no'],
    '고민' : ['무조건먹자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','먹지말자','무조건먹자','무조건먹자']
})
data.to_csv('final_modudak.csv', index=False)
data

# Q. 위 data 변수의 데이터에서 '간장치킨'의 원산지를 미국으로 수정해주세요.
data.loc[2, '원산지'] = '미국'
display(data)

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요     고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   no  무조건먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  yes   먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0   미국  yes   먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  yes   먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  yes   먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  yes   먹지말자
6   양념반후라이드반  13000  10  1300.0  0.2  10400.0  국내산  yes   먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   no  무조건먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   no  무조건먹자

In [10]:
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
display(df)
df.info() # 컬럼의 유형 확인

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


In [11]:
# 단일 컬럼 수동 레이블 인코딩
from sklearn.preprocessing import LabelEncoder # sklearn.preprocessing 라이브러리에서 LabelEncoder 클래스를 임포트
le = LabelEncoder() # 객체를 생성
type(le)
#le.fit(df['원산지'])
#le.transform(df['원산지'])
display(df)
df['원산지'] = le.fit_transform(df['원산지']) # 레이블 인코딩 적용, 국내산: 0, 브라질: 2, 미국: 1
display(df)

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

In [12]:
# 단일 컬럼 수동 레이블 인코딩
le = LabelEncoder()
display(df)
df['살찔까요'] = le.fit_transform(df['살찔까요']) # 레이블 인코딩 적용, no: 0, yes: 1
display(df)

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   no
1  15000  12  1500.0    2  yes
2  14000   9  1600.0    1  yes
3  14000   9  1800.0    0  yes
4  14000  11  1300.0    2  yes
5  13000  10  1400.0    0  yes
6  13000  10  1300.0    0  yes
7  12000  10  1000.0    0   no
8   9900  10  1000.0    0   no

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [14]:
# 다중 컬럼 리스트 변수 적용해 수동 레이블 인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
display(df)
from sklearn.preprocessing import LabelEncoder
cols = ['원산지', '살찔까요'] # 인코딩 컬럼 리스트 변수

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col]) # 컬럼 단위 업데이트

display(df)


가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [33]:
# 다중 컬럼 리스트 변수 적용해 자동 레이블 인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
display(df)
df.info()

df.select_dtypes(include='int64').columns
df.select_dtypes(include='float64').columns
df.select_dtypes(include='object').columns
df.select_dtypes(exclude='object').columns

from sklearn.preprocessing import LabelEncoder # 사이킷런 모듈에서 레이블인코더 메소드 임포트
cols = df.select_dtypes(include='object').columns # object 타입의 모든 컬럼을 리스트로 추출 후 변수에 저장

for col in cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col]) # 컬럼 단위 업데이트

display(df)


가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [68]:
# 단일 컬럼 수동 원-핫 인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False) # 배열 형태 반환 옵션
cat = ohe.fit_transform(df[['원산지']]) # 반드시 "데이터프레임" 형식으로 지정
display(cat)
type(cat) # numpy.ndarray
#ohe.categories_ # 카테고리 출력, ['국내산', '미국', '브라질']
#ohe.get_feature_names_out() # 컬럼명_카테고리 출력, ['원산지_국내산', '원산지_미국', '원산지_브라질']
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out()) # 원-핫 인코딩 "데이터프레임" 생성 => concat()로 합치기 위해
display(df_cat)
df = pd.concat([df, df_cat], axis=1) # 열 기준으로 두 데이터프레임 합치기
df

df = df.drop(['원산지'], axis=1) # 불필요한 object 컬럼 삭제
df

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

원산지_국내산  원산지_미국  원산지_브라질
0      1.0     0.0      0.0
1      0.0     0.0      1.0
2      0.0     1.0      0.0
3      1.0     0.0      0.0
4      0.0     0.0      1.0
5      1.0     0.0      0.0
6      1.0     0.0      0.0
7      1.0     0.0      0.0
8      1.0     0.0      0.0

가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   no      1.0     0.0      0.0
1  15000  12  1500.0  yes      0.0     0.0      1.0
2  14000   9  1600.0  yes      0.0     1.0      0.0
3  14000   9  1800.0  yes      1.0     0.0      0.0
4  14000  11  1300.0  yes      0.0     0.0      1.0
5  13000  10  1400.0  yes      1.0     0.0      0.0
6  13000  10  1300.0  yes      1.0     0.0      0.0
7  12000  10  1000.0   no      1.0     0.0      0.0
8   9900  10  1000.0   no      1.0     0.0      0.0

In [67]:
# 다중 컬럼 데이터 프레임 적용해 수동 원-핫 인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
from sklearn.preprocessing import OneHotEncoder
display(df)
ohe = OneHotEncoder(sparse_output=False)
cat = ohe.fit_transform(df[['원산지', '살찔까요']]) # 다중 컬럼명을 데이터 프레임 형식으로 지정해 처리 => 레이블 인코딩은 "반복문"으로 처리
cat
ohe.categories_ # 카테고리 출력, ['국내산', '미국', '브라질']
#ohe.get_feature_names_out() # 컬럼명_카테고리 출력, ['원산지_국내산', '원산지_미국', '원산지_브라질', '살찔까요_no', '살찔까요_yes']
#df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out()) # 원-핫 인코딩 "데이터 프레임" 생성 => concat()로 합치기 위해
display(df_cat)
df = pd.concat([df, df_cat], axis=1) # 열 기준으로 두 데이터프레임 합치기
df

df = df.drop(['원산지', '살찔까요'], axis=1) # 불필요한 object 컬럼 삭제
df

array(['원산지_국내산', '원산지_미국', '원산지_브라질', '살찔까요_no', '살찔까요_yes'],
      dtype=object)

In [58]:
# 다중 컬럼 리스트[cols] 변수 적용해 자동 원-핫 인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
display(df)
from sklearn.preprocessing import OneHotEncoder
cols = df.select_dtypes(include='object').columns # object 타입의 모든 컬럼을 리스트로 추출
cols
df[cols]
ohe = OneHotEncoder(sparse_output=False)
cat = ohe.fit_transform(df[cols]) # 원핫인코딩 결과 값
display(cat)
#ohe.categories_ # 카테고리 출력, ['국내산', '미국', '브라질']
#ohe.get_feature_names_out() # 컬럼명_카테고리 출력, ['원산지_국내산', '원산지_미국', '원산지_브라질', '살찔까요_no', '살찔까요_yes']
df_cat = pd.DataFrame(cat, columns=ohe.get_feature_names_out()) # 원-핫 인코딩 "데이터프레임" 생성 => concat()로 합치기 위해
df_cat

df = pd.concat([df, df_cat], axis=1) # 열 기준으로 두 데이터프레임 합치기
df.head()

df = df.drop(cols, axis=1) # 불필요한 object 컬럼 삭제
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   no
1  15000  12  1500.0  브라질  yes
2  14000   9  1600.0   미국  yes
3  14000   9  1800.0  국내산  yes
4  14000  11  1300.0  브라질  yes
5  13000  10  1400.0  국내산  yes
6  13000  10  1300.0  국내산  yes
7  12000  10  1000.0  국내산   no
8   9900  10  1000.0  국내산   no

array([[1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 1., 0.]])

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

In [ ]:
# 판다스를 이용한 원핫인코딩
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()
df.head()
df = pd.get_dummies(df).copy()
display(df)

가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1
5  13000  10  1400.0        1       0        0        0         1
6  13000  10  1300.0        1       0        0        0         1
7  12000  10  1000.0        1       0        0        1         0
8   9900  10  1000.0        1       0        0        1         0

In [ ]:
# 수치형 데이터를 전처리하는 방법 => 표준화
# 표준화는 데이터를 표준 정규분포로 변환해 데이터 분석의 편향을 줄이기 위해 사용.
df2 = df.copy()
#display(df2)
#df2.head()
from sklearn.preprocessing import StandardScaler
cols = ['가격', '호수', '칼로리']
scaler = StandardScaler()
df2[cols] = scaler.fit_transform(df2[cols])
display(df2)

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

In [ ]:
# 수치형 데이터를 전처리하는 방법 => 표준화 => 정규화
# 정규화는 데이터의 크기를 조정하는 과정으로 데이터 분석의 효율성을 높이기 위해 사용되는 중요한 방법
# 정규화된 데이터의 크기는 모두 0에서 1 사이. 이로 인해 데이터 비교가 용이함.
# 표준화만, 정규화만, 또는 표준화 & 정규화 Case By Case
from sklearn.preprocessing import MinMaxScaler
cols = ['가격', '호수', '칼로리']
scaler = MinMaxScaler()
df2[cols] = scaler.fit_transform(df2[cols])
display(df2)

가격        호수    칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_no  살찔까요_yes
0  1.000000  0.666667  0.250        1       0        0        1         0
1  0.836066  1.000000  0.625        0       0        1        0         1
2  0.672131  0.000000  0.750        0       1        0        0         1
3  0.672131  0.000000  1.000        1       0        0        0         1
4  0.672131  0.666667  0.375        0       0        1        0         1
5  0.508197  0.333333  0.500        1       0        0        0         1
6  0.508197  0.333333  0.375        1       0        0        0         1
7  0.344262  0.333333  0.000        1       0        0        1         0
8  0.000000  0.333333  0.000        1       0        0        1         0

In [ ]:
# 사이킷런 데이터셋 불러오기
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
#display(dataset)

# 피처(컬럼) 이름 확인
dataset.feature_names

# 타겟(레이블, 학습 데이터) 확인
dataset.target

# 데이터 확인
dataset.data[:2]

# 데이터프레임으로 만들기
cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
#display(cancer_df)

# 타겟 추가하기
#display(dataset.target)
cancer_df['target'] = dataset.target
cancer_df.head()

# 사이킷런에서 제공하는 데이터셋 확인 (load_*)
import sklearn.datasets
sklearn.datasets.__all__


['clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_species_distributions',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_rcv1',
 'fetch_kddcup99',
 'fetch_openml',
 'get_data_home',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_breast_cancer',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_circles',
 'make_classification',
 'make_checkerboard',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll']

In [ ]:
# 당료병 데이터 불러오기
from sklearn.datasets import load_diabetes
dataset = load_diabetes()
#display(dataset)

# 피처(컬럼) 이름 확인 하기
dataset.feature_names

# 타겟(레이블, 학습 데이터) 확인
dataset.target

# 데이터프레임으로 만들기
diabetes_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
#display(diabetes_df)


# 타겟 추가하기
diabetes_df['target'] = dataset.target
diabetes_df.head()


age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [ ]:
# 머신러닝 분류
# 검증(validation) 데이터 분리
# X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
# X_test을 통해 예측
# y_test로 평가/검증
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    cancer_df.drop('target', axis=1), cancer_df['target'], test_size=0.3, random_state=1004)

# 훈련(training) 데이터 확인: (X) => 훈련 데이터(X_train)와 예측 데이터(X_test)
X_train.head()

# 학습(learning) 데이터 확인: 레이블(y) => 학습 데이터(y_train)와 검증 데이터(y_test)
y_train.head()

# 데이터 크기
X_train.shape, X_test.shape, y_train.shape, y_test.shape
# 여기까지가 학습과 평가에 필요한 데이터를 분리하는 작업


((398, 30), (171, 30), (398,), (171,))

In [ ]:
# 1. 머신러닝: 의사결정나무(Decision Tree)
# X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
# X_test을 통해 예측
# y_test로 평가

# 머신러닝 분류
# 의사결정트리 모델
from sklearn.tree import DecisionTreeClassifier

# 모델 학습
model = DecisionTreeClassifier()

# 훈련 & 학습, X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
model.fit(X_train, y_train)

# 예측값, X_test을 통해 예측
pred = model.predict(X_test)
display(pred)

# 평가(Accuracy), y_test로 평가
# 정확도 accuracy_score(실제값, 예측값)
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)


array([1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

0.8947368421052632

In [ ]:
# 2. 머신러닝: 회귀분석
# 검증 데이터 분리
# X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
# X_test을 통해 예측
# y_test로 평가
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    diabetes_df.drop('target', axis=1), diabetes_df['target'], test_size=0.3, random_state=1004)

# 훈련 데이터 확인
X_train.head()

# 학습 데이터 확인
y_train.head()

# 데이터 크기
X_train.shape, X_test.shape, y_train.shape, y_test.shape
# 여기까지가 학습과 평가에 필요한 데이터를 분리하는 작업


((309, 10), (133, 10), (309,), (133,))

In [ ]:
# 선형회귀(Linear Regression)
# 머신러닝(회귀)
from sklearn.linear_model import LinearRegression

# 모델 학습
model = LinearRegression()

# 훈련 & 학습, X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
model.fit(X_train, y_train)

# 예측값, X_test을 통해 예측
pred = model.predict(X_test)
display(pred)


array([128.42468606, 135.08774266, 154.78504343, 106.09306564,
       149.54478558, 165.32708009, 140.29166154, 167.9600165 ,
        69.44851384, 189.42811434, 144.98692247, 150.10700196,
       211.15983244, 108.59257071, 160.3856331 , 154.09855476,
       198.78116874, 101.16062264, 165.82852734, 196.03659567,
       147.16472505, 108.25668788, 207.27889551, 127.53191954,
       181.85997027, 228.49975565,  86.59589481, 155.35081963,
       182.49593133, 182.96390209, 207.63119699, 199.81134435,
       157.35809543,  61.82465786,  88.11634158,  95.75033061,
       134.03120864,  85.95903914, 177.69650387, 249.40014721,
       171.77206628, 204.71572412, 239.12149428,  89.24927278,
       244.20385113, 180.36498587, 161.10608699, 119.14846149,
       102.81815844, 153.35400825, 129.06743815, 208.80206598,
       107.93927973, 138.81355171, 166.04217088,  86.04455248,
       181.03094575, 117.97907348,  79.04947426, 127.20387612,
       194.05986421, 205.13463546, 233.84790901,  48.53

In [ ]:
# 평가(mse)
# 정확도 mean_squared_error (실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

3229.454787929743

In [ ]:
# Q. 처음 만들었던 'final_modudak.csv' 데이터로 치킨 "가격" 예측을 하는 회귀 모델을 만들어보겠습니다.
# 빈칸을 채워주세요.

# 데이터 로드
data = pd.read_csv('final_modudak.csv')

# 모델에 사용할 칼럼 지정
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()

# 원핫인코딩
df = pd.get_dummies(df)
df

# test데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('가격', axis=1), df['가격'], test_size=0.3, random_state=1004) # Train:Test = 7:3

# 머신러닝(회귀)
# 원하는 모델 라이브러리를 불러오세요.
from sklearn.linear_model import LinearRegression

# 원하는 모델을 선택해 보세요.
model = LinearRegression()

# 훈련 & 학습, X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
model.fit(X_train, y_train)

# 예측
pred = model.predict(X_test)
display(pred)

# test데이터의 실제값과 예측값 비교
pd.DataFrame({'실제값' : y_test, '예측값' : pred})

# 평가(mse)
# 정확도 mean_squared_error (실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

array([12750. , 12812.5, 12000. ])

5002552.083333342

In [ ]:
# Q. 처음 만들었던 'final_modudak.csv' 데이터로 치킨 "가격" 예측을 하는 회귀 모델을 만들어보겠습니다.
# 표준하 및 종규화 전처리 작업 적용

# 데이터 로드
data = pd.read_csv('final_modudak.csv')

# 모델에 사용할 칼럼 지정
df = data[['가격', '호수', '칼로리', '원산지', '살찔까요']].copy()

# 원핫인코딩
df = pd.get_dummies(df)


# 수치형 데이터를 전처리하는 방법 => 표준화
df2 = df.copy()
from sklearn.preprocessing import StandardScaler
cols = ['가격', '호수', '칼로리']
scaler = StandardScaler()
df2[cols] = scaler.fit_transform(df2[cols])

# 수치형 데이터를 전처리하는 방법 => 표준화 => 정규화
# 표준화만, 정규화만, 또는 표준화 & 정규화 Case By Case
from sklearn.preprocessing import MinMaxScaler
cols = ['가격', '호수', '칼로리']
scaler = MinMaxScaler()
df2[cols] = scaler.fit_transform(df2[cols])

# test데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    df2.drop('가격', axis=1), df2['가격'], test_size=0.3, random_state=1004) # Train:Test = 7:3

# 머신러닝(회귀)
# 원하는 모델 라이브러리를 불러오세요.
from sklearn.linear_model import LinearRegression

# 원하는 모델을 선택해 보세요.
model = LinearRegression()

# 훈련 & 학습, X_train, y_train 데이터를 이용해 머신러닝 훈련 & 학습
model.fit(X_train, y_train)

# 예측
pred = model.predict(X_test)
display(pred)

# test데이터의 실제값과 예측값 비교
pd.DataFrame({'실제값' : y_test, '예측값' : pred})

# 평가(mse)
# 정확도 mean_squared_error (실제값, 예측값)
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, pred)

array([0.46721311, 0.47745902, 0.3442623 ])

0.13444106646958706